export const Permissions = {
    DASHBOARD: {
        VIEW: 'dashboard:view',
    },
    USER: {
        LIST: 'user:list',
        VIEW: 'user:view',
        EDIT: 'user:edit',
        DELETE: 'user:delete',
        CREATE: 'user:create',
    },
    STUDENT: {
        LIST: 'student:list',
        VIEW: 'student:view',
        EDIT: 'student:edit',
        DELETE: 'student:delete',
        CREATE: 'student:create',
        ATTENDANCE: {
            LIST: 'student:attendance:list',
            VIEW: 'student:attendance:view',
            EDIT: 'student:attendance:edit',
            DELETE: 'student:attendance:delete',
            CREATE: 'student:attendance:create',
        },
        AUTHORIZATION: {
            LIST: 'student:authorization:list',
            VIEW: 'student:authorization:view',
            EDIT: 'student:authorization:edit',
            DELETE: 'student:authorization:delete',
            CREATE: 'student:authorization:create',
        },
        TUTORSHIP: {
            LIST: 'student:tutorship:list',
            VIEW: 'student:tutorship:view',
            EDIT: 'student:tutorship:edit',
            DELETE: 'student:tutorship:delete',
            CREATE: 'student:tutorship:create',
        },
        SANCTION: {
            LIST: 'student:sanction:list',
            VIEW: 'student:sanction:view',
            EDIT: 'student:sanction:edit',
            DELETE: 'student:sanction:delete',
            CREATE: 'student:sanction:create',
        },
    },
    GUARDIAN: {
        LIST: 'guardian:list',
        VIEW: 'guardian:view',
        EDIT: 'guardian:edit',
        DELETE: 'guardian:delete',
        CREATE: 'guardian:create',
    },
    INVOICE: {
        LIST: 'student:invoice:list',
        VIEW: 'student:invoice:view',
        EDIT: 'student:invoice:edit',
        DELETE: 'student:invoice:delete',
        CREATE: 'student:invoice:create',
    },
    KIOSK: {
        VIEW: 'kiosk:view',
    },
    SETTINGS: {
        VIEW: 'settings:view',
        EDIT: 'settings:edit',
        ROLES: {
            LIST: 'settings:roles:list',
            VIEW: 'settings:roles:view',
            EDIT: 'settings:roles:edit',
            DELETE: 'settings:roles:delete',
            CREATE: 'settings:roles:create',
        },
    },
};
