export const Permissions = {
    DASHBOARD: {
        VIEW: 'dashboard:view',
    },
    USER: {
        LIST: 'user:list',
        VIEW: 'user:view',
        EDIT: 'user:edit',
        DELETE: 'user:delete',
        CREATE: 'user:create',
    },
    STUDENT: {
        LIST: 'student:list',
        VIEW: 'student:view',
        EDIT: 'student:edit',
        DELETE: 'student:delete',
        CREATE: 'student:create',
        ATTENDANCE: {
            LIST: 'student:attendance:list',
            VIEW: 'student:attendance:view',
            EDIT: 'student:attendance:edit',
            DELETE: 'student:attendance:delete',
            CREATE: 'student:attendance:create',
        },
        AUTHORIZATION: {
            LIST: 'student:authorization:list',
            VIEW: 'student:authorization:view',
            EDIT: 'student:authorization:edit',
            DELETE: 'student:authorization:delete',
            CREATE: 'student:authorization:create',
        },
        TUTORSHIP: {
            LIST: 'student:tutorship:list',
            VIEW: 'student:tutorship:view',
            EDIT: 'student:tutorship:edit',
            DELETE: 'student:tutorship:delete',
            CREATE: 'student:tutorship:create',
        },
        SANCTION: {
            LIST: 'student:sanction:list',
            VIEW: 'student:sanction:view',
            EDIT: 'student:sanction:edit',
            DELETE: 'student:sanction:delete',
            CREATE: 'student:sanction:create',
        },
    },
    GUARDIAN: {
        LIST: 'guardian:list',
        VIEW: 'guardian:view',
        EDIT: 'guardian:edit',
        DELETE: 'guardian:delete',
        CREATE: 'guardian:create',
    },
    INVOICE: {
        LIST: 'student:invoice:list',
        VIEW: 'student:invoice:view',
        EDIT: 'student:invoice:edit',
        DELETE: 'student:invoice:delete',
        CREATE: 'student:invoice:create',
    },
    KIOSK: {
        VIEW: 'kiosk:view',
    },
    SETTINGS: {
        VIEW: 'settings:view',
        EDIT: 'settings:edit',
        ROLES: {
            LIST: 'settings:roles:list',
            VIEW: 'settings:roles:view',
            EDIT: 'settings:roles:edit',
            DELETE: 'settings:roles:delete',
            CREATE: 'settings:roles:create',
        },
    },
};

export const PermissionsES = [
    { label: 'DASHBOARD', value: 'Dashboard' },
    { label: 'USER', value: 'Usuarios' },
    { label: 'CAMPAIGN', value: 'Campañas' },
    { label: 'CLIENT', value: 'Clientes' },
    { label: 'OPPORTUNITY', value: 'Oportunidades' },
    { label: 'PROJECT', value: 'Proyectos' },
    { label: 'CONTRACT', value: 'Contratos' },
    { label: 'TASK', value: 'Tareas' },
    { label: 'CALENDAR', value: 'Calendario' },
    { label: 'REPORTS', value: 'Reportes' },
    { label: 'SETTINGS', value: 'Ajustes' },
    { label: 'FILE', value: 'Documentos' },
    { label: 'TEAM', value: 'Equipo de trabajo' },
    { label: 'PRODUCT', value: 'Productos' },
    { label: 'NOTE', value: 'Notas' },
    { label: 'INTERACTION', value: 'Interacciones' },
    { label: 'VIEW', value: 'Ver' },
    { label: 'EDIT', value: 'Editar' },
    { label: 'DELETE', value: 'Eliminar' },
    { label: 'CREATE', value: 'Crear' },
    { label: 'LIST', value: 'Listar' },
    { label: 'CONTACT', value: 'Contacto' },
    { label: 'SHOW_ALL', value: 'Mostrar todo' },
    { label: 'NEXT_PHASE', value: 'Siguiente fase' },
    { label: 'REJECT', value: 'Rechazar' },
    { label: 'TEAM', value: 'Equipo' },
    { label: 'REJECT', value: 'Rechazar' },
    { label: 'ROLES', value: 'Roles' },
    { label: 'PERMISSIONS', value: 'Permisos' },
    { label: 'GUARDIAN', value: 'Tutores' },
    { label: 'STUDENT', value: 'Alumnos' },
    { label: 'INVOICE', value: 'Facturas' },
    { label: 'TUTORSHIP', value: 'Tutorías' },
    { label: 'SANCTION', value: 'Sanciones' },
    { label: 'AUTHORIZATION', value: 'Autorizaciones' },
    { label: 'ATTENDANCE', value: 'Asistencias' },
    { label: 'KIOSK', value: 'Puesto de control' },
];
