export const Permissions = {
    DASHBOARD: {
        VIEW: 'dashboard:view',
    },
    USER: {
        LIST: 'user:list',
        VIEW: 'user:view',
        EDIT: 'user:edit',
        DELETE: 'user:delete',
        CREATE: 'user:create',
    },
    SETTINGS: {
        VIEW: 'settings:view',
        EDIT: 'settings:edit',
        ROLES: {
            LIST: 'settings:roles:list',
            VIEW: 'settings:roles:view',
            EDIT: 'settings:roles:edit',
            DELETE: 'settings:roles:delete',
            CREATE: 'settings:roles:create',
        },
    },
};

export const PermissionsES = [
    { label: 'DASHBOARD', value: 'Dashboard' },
    { label: 'USER', value: 'Usuarios' },
    { label: 'CAMPAIGN', value: 'Campañas' },
    { label: 'CLIENT', value: 'Clientes' },
    { label: 'OPPORTUNITY', value: 'Oportunidades' },
    { label: 'PROJECT', value: 'Proyectos' },
    { label: 'CONTRACT', value: 'Contratos' },
    { label: 'TASK', value: 'Tareas' },
    { label: 'CALENDAR', value: 'Calendario' },
    { label: 'REPORTS', value: 'Reportes' },
    { label: 'SETTINGS', value: 'Ajustes' },
    { label: 'FILE', value: 'Documentos' },
    { label: 'TEAM', value: 'Equipo de trabajo' },
    { label: 'PRODUCT', value: 'Productos' },
    { label: 'NOTE', value: 'Notas' },
    { label: 'INTERACTION', value: 'Interacciones' },
    { label: 'VIEW', value: 'Ver' },
    { label: 'EDIT', value: 'Editar' },
    { label: 'DELETE', value: 'Eliminar' },
    { label: 'CREATE', value: 'Crear' },
    { label: 'LIST', value: 'Listar' },
    { label: 'CONTACT', value: 'Contacto' },
    { label: 'SHOW_ALL', value: 'Mostrar todo' },
    { label: 'NEXT_PHASE', value: 'Siguiente fase' },
    { label: 'REJECT', value: 'Rechazar' },
    { label: 'TEAM', value: 'Equipo' },
    { label: 'REJECT', value: 'Rechazar' },
    { label: 'ROLES', value: 'Roles' },
];
