-- AlterTable
ALTER TABLE `NT_StudentsSTU` ADD COLUMN `bed` VARCHAR(100) NULL,
    ADD COLUMN `block` VARCHAR(100) NULL,
    ADD COLUMN `floor` VARCHAR(100) NULL,
    ADD COLUMN `room` VARCHAR(100) NULL;
