-- AlterTable
ALTER TABLE `NT_UsersUSR` ADD COLUMN `roleId` VARCHAR(191) NULL;

-- AddForeignKey
ALTER TABLE `NT_UsersUSR` ADD CONSTRAINT `NT_UsersUSR_roleId_fkey` FOREIGN KEY (`roleId`) REFERENCES `NT_RolesROL`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
